apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mynamespace-poi-gateway-app-dev
  annotations:
    argocd/app-name: mynamespace-poi-gateway-app-dev
    backstage.io/kubernetes-id: mynamespace-poi-gateway-app
    backstage.io/kubernetes-namespace: mynamespace
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: WindTurbineInc/mynamespace-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.wearedevs.rl97.p1.openshiftapps.com/dev-pipelines/ns/mynamespace/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.wearedevs.rl97.p1.openshiftapps.com/k8s/ns/mynamespace/deployments/mynamespace-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.wearedevs.rl97.p1.openshiftapps.com/#https://github.com/WindTurbineInc/mynamespace-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/blues-man"
